# Generated by Django 4.1.3 on 2023-05-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_news_views_alter_comment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='views',
        ),
    ]
